GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/62325d96869cb04626115df4

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Vignesh",
    "subscriberToChannel":"Web Dev"
}

###


DELETE http://localhost:3000/subscribers/62325d96869cb04626115df4

###
PATCH http://localhost:3000/subscribers/623256841dff9629a44ab9b5
Content-Type: application/json

{
    "name": "Vigneshraja",
    "subscriberToChannel":"Web Dev"
}

###

